# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-d3d58b11-aab6-48ca-9a1f-91cffb962c9c";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-d3d58b11-aab6-48ca-9a1f-91cffb962c9c".device =
    "/dev/disk/by-uuid/d3d58b11-aab6-48ca-9a1f-91cffb962c9c";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2B6A-D469";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-4afbcf82-b71b-4208-a2de-732ecf36f404"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
