# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "12206695fbabe2c3f981ea79d97afe8d4fdb7790773a4153543c63ac7e0d11e564c7";
    path = fetchgit {
      url = "https://github.com/freref/fastb64z";
      rev = "fa3f34a4528609a8778124641b080e90d93c357a";
      hash = "sha256-yz1XRRsX0Uh7lmPBKSkzDJIxValM5VvbI5avpa530nE=";
    };
  }
  {
    name = "1220b0c4f4a5f3df2b1268a9da04bc901ede4f8bd2938e846ee1e88783ed57cee79a";
    path = fetchzip {
      url = "https://github.com/freref/fzwatch/archive/refs/heads/master.tar.gz";
      hash = "sha256-rBbCdwTaq0DVBiUMzq2q72jgtaTIdjqivMI8dq+BaPM=";
    };
  }
  {
    name = "1220feaa655e14cbb4baf59fe746f09a17fc6949be46ad64dd5044982f4fc1bb57c7";
    path = fetchgit {
      url = "https://github.com/rockorager/libvaxis";
      rev = "d409f2f168192374aa7c625f61f6fe64fdb66818";
      hash = "sha256-VqpfceAkx04/J4RJpcUTcNZZlJTepu6OQbEbneRGWBY=";
    };
  }
]
