# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, return, exec, alacritty
bind = $mainMod, Q, killactive, 
bind = $mainMod, N, exec, dolphin
bind = $mainMod, W, exec, firefox
bind = $mainMod, V, togglefloating, 
bind = $mainMod, D, exec, wofi --show drun
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, F, fullscreen,
bind = $mainMod, L, exec, swaylock -C ~/.config/swaylock/config
bind = $mainMod, S, exec, spotify
bind = $mainMod, T, exec, thunderbird
bind = SUPER_SHIFT, Q, exit 

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, Ampersand, workspace, 1
bind = $mainMod, Eacute, workspace, 2
bind = $mainMod, Quotedbl, workspace, 3
bind = $mainMod, Apostrophe, workspace, 4
bind = $mainMod, Parenleft, workspace, 5
bind = $mainMod, Minus, workspace, 6
bind = $mainMod, Egrave, workspace, 7
bind = $mainMod, Underscore, workspace, 8
bind = $mainMod, Ccedilla, workspace, 9
bind = $mainMod, Agrave, workspace, 10

# Backlight
binde = , XF86MonBrightnessUp, exec, brightnessctl set +5%
binde = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
bindel = , XF86KbdBrightnessUp, exec, brightnessctl -d asus::kbd_backlight set +1
bindel = , XF86KbdBrightnessDown, exec, brightnessctl -d asus::kbd_backlight set 1-

# Screenshot
bind = , print, exec, grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp)" - | swappy -f -

# Audio control
bindle= , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
bindle= , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, Ampersand, movetoworkspace, 1
bind = $mainMod SHIFT, Eacute, movetoworkspace, 2
bind = $mainMod SHIFT, Quotedbl, movetoworkspace, 3
bind = $mainMod SHIFT, Apostrophe, movetoworkspace, 4
bind = $mainMod SHIFT, Parenleft, movetoworkspace, 5
bind = $mainMod SHIFT, Minus, movetoworkspace, 6
bind = $mainMod SHIFT, Egrave, movetoworkspace, 7
bind = $mainMod SHIFT, Underscore, movetoworkspace, 8
bind = $mainMod SHIFT, Ccedilla, movetoworkspace, 9
bind = $mainMod SHIFT, Agrave, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
