keys:
  - &users:
    - &ciflire age17pemv93as5jtu950lz6n229uwg5q3dyjph0c7gntc7wxgy9nre3srmjfhy
  - &hosts:
    - &vivobook14 age14hrpm6pjm4nm60x3jjqucllgzz7nm9mfje0slekxg8v5at2ajgmqdps7l3
    - &corsair age1j43s4ytd4mhhcww6dkyamdgaep2p7r4kz3khk3drqc5fktyh4g3qu9ycfc
    - &aorus age145y5fffpkfd65xsqxrhhgnwhrtk065jrxfa58mjpx9wypr67hqqsglm3c2
creation_rules:
  - path_regex: secrets.yaml$|weatherapi.json$|.svg$
    key_groups:
    - age:
      - *ciflire
      - *vivobook14
      - *corsair
      - *aorus
