keys:
  - &users:
    - &ciflire age17pemv93as5jtu950lz6n229uwg5q3dyjph0c7gntc7wxgy9nre3srmjfhy
  - &hosts:
    - &vivobook14 age1y0ryt0jxw0xw4lzz3tpyqngystkh46wv2ym68n0r38z36rx9sumqt2ex3n
    - &corsair age1j43s4ytd4mhhcww6dkyamdgaep2p7r4kz3khk3drqc5fktyh4g3qu9ycfc
creation_rules:
  - path_regex: secrets.yaml$|weatherapi.json$|.svg$
    key_groups:
    - age:
      - *ciflire
      - *vivobook14
      - *corsair

